version: "3.6"
services:

  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - 8080:8080
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    depends_on:
      - "postgres"
    restart: always

  postgres:
    image: postgres:13
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment: 
    - POSTGRES_PASSWORD=postgres
  
volumes:
  db_data:
